### PR TITLE
Activate ansible-lint via zuul job

### PR DESCRIPTION
**Pull request by ra-beer**
- Add asnible-linting-rules
- Activate zuul job ansible-lint
- Partly osism/issues#395

Signed-off-by: Ramona Beermann <ramona.beermann@osism.tech>

### CODE REVIEW

**Comment by ra-beer** [comment]
recheck

**Comment by berendt** [comment]
Why do we disable the update-gitea-mirrors job with this PR?

**Comment by tibeer** [comment]
The job was never really used. Also it was developed for the old zuul (zuul.osism.xyz). The successor for this is found in https://github.com/osism/scripts/tree/main/gitea. But there is currenly no automation that executes this. Created an issue for that: https://github.com/osism/scripts/issues/12

**Comment by tibeer** [comment]
To allow future updates of the gitea mirror, I created https://github.com/osism/scripts/issues/12

**Pull request merged**
