### PR TITLE
Added harbor automated setup

### LINKED ISSUE #2: harbor: add replication rules

### LINKED ISSUE #3: harbor: add robot accounts

### PR DESCRIPTION
**Pull request by tibeer**
Robot accounts, replication rules, etc.

closes #2 
closes #3

Signed-off-by: Tim Beermann <beermann@osism.tech>

### CODE REVIEW

**Comment by berendt** [comment]
@tibeer Added the check-python-syntax workflow. please do rebase

**Comment by tibeer** [comment]
@berendt done.

**Comment by tibeer** [comment]
@berendt done

**Comment by berendt** [comment]
@tibeer A requirements.txt is missing

**Comment by tibeer** [comment]
@berendt solved.

**Comment by berendt** [comment]
This must be placed in the commit message. Not in the PR message. Added it there before the merge. Please add it in the future. I will add a section to the development guide.

```
Closes #2
Closes #3
```

**Pull request merged**
